import enum


class Severity(str, enum.Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class FindingCategory(str, enum.Enum):
    TECHNICAL = "TECHNICAL"
    SEO = "SEO"
    LOCAL = "LOCAL"
    AIO = "AIO"
    AUTHORITY = "AUTHORITY"
    CONTENT = "CONTENT"
    INTERNAL_LINKING = "INTERNAL_LINKING"
    CONVERSION = "CONVERSION"
    TRUST = "TRUST"
    STRUCTURED_DATA = "STRUCTURED_DATA"


class OpportunityStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    FIXED = "FIXED"
    IGNORED = "IGNORED"


class TaskStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"


class EvidenceStrength(str, enum.Enum):
    VERY_STRONG = "VERY_STRONG"
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    WEAK = "WEAK"
    MISSING = "MISSING"


class QueryIntent(str, enum.Enum):
    LOCAL_RECOMMENDATION = "LOCAL_RECOMMENDATION"
    SERVICE_RECOMMENDATION = "SERVICE_RECOMMENDATION"
    PERSONAL_TRAINER_RECOMMENDATION = "PERSONAL_TRAINER_RECOMMENDATION"
    EXECUTIVE_HEALTH = "EXECUTIVE_HEALTH"
    CORRECTIVE_EXERCISE = "CORRECTIVE_EXERCISE"
    TRANSFORMATION = "TRANSFORMATION"
    NUTRITION = "NUTRITION"
    AGE_SPECIFIC = "AGE_SPECIFIC"
    LOCATION_SPECIFIC = "LOCATION_SPECIFIC"
    GENERAL_INFORMATION = "GENERAL_INFORMATION"
    COMPARISON = "COMPARISON"
    OTHER = "OTHER"


class QueryCluster(str, enum.Enum):
    EXECUTIVE = "EXECUTIVE"
    LOCAL = "LOCAL"
    CORRECTIVE_EXERCISE = "CORRECTIVE_EXERCISE"
    IN_HOME = "IN_HOME"
    NUTRITION = "NUTRITION"
    TRANSFORMATION = "TRANSFORMATION"
    AGE_SPECIFIC = "AGE_SPECIFIC"
    GENERAL = "GENERAL"
